const express = require("express");
const bodyParser = require("body-parser");
const app = express();
const { PORT } = require("./config/serverConfig");
const apiRoutes = require("./routes/index");
const db = require("./models/index");
const RestaurantService = require("./services/restaurant-service");
const { report } = require("./routes/index");

const setupAndStartServer = () => {
  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded({ extended: true }));
  app.use("/api", apiRoutes);
  app.listen(PORT, () => {
    console.log(`Server started on port ${PORT}`);
    const repo = new RestaurantService();

    const data = [
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "229832",
          name: "Khanna's",
          uuid: "ececad40-123f-4ba9-ac75-80286d6c844c",
          city: "1",
          area: "Brookefield",
          totalRatingsString: "5000+ ratings",
          cloudinaryImageId: "oy1fu3a6ztlv9mqpeq5u",
          cuisines: ["North Indian", "Punjabi", "Tandoor"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          slaString: "34 MINS",
          lastMileTravel: 4.699999809265137,
          slugs: {
            restaurant: "homms-desi-marathahalli-marathahalli",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "5/2, Ground Floor, Vyjayanthi Mala complex, Varthur main road, Behind Swiggy Marathali Hub and Apollo Clinic, Bangalore-560066",
          locality: "BEML Layout",
          parentId: 14519,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 4900,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 4900,
            message: "",
            title: "Delivery Charge",
            amount: "4900",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=6978009~p=1~eid=00000188-96ed-70c5-0710-ca88004c010f",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "4.6 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "10% OFF",
            subHeader: "",
            discountTag: "FLAT DEAL",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "229832",
            deliveryTime: 34,
            minDeliveryTime: 34,
            maxDeliveryTime: 34,
            lastMileTravel: 4.699999809265137,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.2",
          totalRatings: 5000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "221738",
          name: "Meghana Foods",
          uuid: "106f4556-6804-4554-8c68-ee875d6acf65",
          city: "1",
          area: "Brookefield",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "aqsnrylokzpn45qhg1pb",
          cuisines: [
            "Biryani",
            "Andhra",
            "South Indian",
            "North Indian",
            "Chinese",
            "Seafood",
          ],
          tags: [],
          costForTwo: 50000,
          costForTwoString: "₹500 FOR TWO",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          slaString: "31 MINS",
          lastMileTravel: 6.5,
          slugs: {
            restaurant: "meghana-foods-mahadevpura-mahadevpura",
            city: "bangalore",
          },
          cityState: "1",
          address: "Raj Pinnacle, Mahadevapura, Bengaluru, Karnataka, India",
          locality: "Mahadevpura",
          parentId: 635,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 7600,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 7600,
            message: "",
            title: "Delivery Charge",
            amount: "7600",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "6.5 kms",
          hasSurge: false,
          sla: {
            restaurantId: "221738",
            deliveryTime: 31,
            minDeliveryTime: 31,
            maxDeliveryTime: 31,
            lastMileTravel: 6.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.3",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "689529",
          name: "The Indian Food Story",
          uuid: "8c27b03f-6046-4b84-abc5-495e4d1dc94a",
          city: "1",
          area: "Marathahalli",
          totalRatingsString: "500+ ratings",
          cloudinaryImageId: "8807626469b8e4a8632bf20fc04202a3",
          cuisines: [
            "North Indian",
            "Punjabi",
            "Biryani",
            "Desserts",
            "Chaat",
            "Snacks",
          ],
          tags: [],
          costForTwo: 45000,
          costForTwoString: "₹450 FOR TWO",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          slaString: "26 MINS",
          lastMileTravel: 4.699999809265137,
          slugs: {
            restaurant: "the-indian-food-story-marathahalli-marathahalli",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "No. 5/3, Thubarahalli Village,Varthur Hobli, Bengaluru east Taluk, Bangalore Urban, Karnataka-560066",
          locality: "Varthur Hobli",
          parentId: 294086,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 4900,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 4900,
            message: "",
            title: "Delivery Charge",
            amount: "4900",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=7059115~p=4~eid=00000188-96ed-70c5-0710-ca89004c0479",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "4.6 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "50% OFF",
            subHeader: "UPTO ₹100",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "689529",
            deliveryTime: 26,
            minDeliveryTime: 26,
            maxDeliveryTime: 26,
            lastMileTravel: 4.699999809265137,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.0",
          totalRatings: 500,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "61580",
          name: "Imperio Restaurant",
          uuid: "310bf316-1c3b-4408-b4a7-d6d40cb7b70b",
          city: "1",
          area: "Whitefield",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "a1629b9c7f59577a55411e94425c6d99",
          cuisines: [
            "Chinese",
            "South Indian",
            "North Indian",
            "Continental",
            "Desserts",
            "Kerala",
            "Beverages",
            "Mughlai",
            "Seafood",
            "Punjabi",
            "Hyderabadi",
            "Singaporean",
            "Thai",
          ],
          tags: [],
          costForTwo: 50000,
          costForTwoString: "₹500 FOR TWO",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          slaString: "29 MINS",
          lastMileTravel: 4.599999904632568,
          slugs: {
            restaurant: "imperio-restaurant-whitefield-whitefield-2",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "No. 101/9, Apple City, Hoskote Main Road, near H.P. Petrol Bunk, Chaitanya Ananya, Seegehalli, Kadugodi, Bengaluru, Karnataka 560067",
          locality: "Seegehalli",
          parentId: 5610,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 4900,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 4900,
            message: "",
            title: "Delivery Charge",
            amount: "4900",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "4.5 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "20% OFF",
            subHeader: "UPTO ₹50",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "61580",
            deliveryTime: 29,
            minDeliveryTime: 29,
            maxDeliveryTime: 29,
            lastMileTravel: 4.599999904632568,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.8",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "361882",
          name: "ITC Master Chef Creations",
          uuid: "edb13d08-f105-46ec-9b72-39a088d1ab86",
          city: "1",
          area: "Whitefield",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "rw3jwbtjdej6xrwdhxyj",
          cuisines: [
            "North Indian",
            "Biryani",
            "Indian",
            "Punjabi",
            "Chaat",
            "Kebabs",
            "Tandoor",
            "Mughlai",
            "Desserts",
            "Snacks",
          ],
          tags: [],
          costForTwo: 65000,
          costForTwoString: "₹650 FOR TWO",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          slaString: "24 MINS",
          lastMileTravel: 4.099999904632568,
          slugs: {
            restaurant: "itc-master-chef-creations-thubarahalli-whitefield",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "Counter 16, Napa East,No 710 Varthur Road,Thubrahalli,Whitefield,Bengaluru,Karnataka-560066",
          locality: "Thubarahalli",
          parentId: 11992,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 4900,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 4900,
            message: "",
            title: "Delivery Charge",
            amount: "4900",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=7050648~p=7~eid=00000188-96ed-70c5-0710-ca8a004c074b",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "4 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "₹150 OFF",
            subHeader: "ABOVE ₹899",
            discountTag: "FLAT DEAL",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "361882",
            deliveryTime: 24,
            minDeliveryTime: 24,
            maxDeliveryTime: 24,
            lastMileTravel: 4.099999904632568,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.3",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "1221",
          name: "Biryani Day",
          uuid: "1dec917e-3f4b-479b-b4db-f7095248bbd8",
          city: "1",
          area: "Marathahalli",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "ucpbuzrvhg0ire3h9hwu",
          cuisines: ["North Indian", "Chinese", "Andhra", "Biryani"],
          tags: [],
          costForTwo: 25000,
          costForTwoString: "₹250 FOR TWO",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          slaString: "30 MINS",
          lastMileTravel: 7.5,
          slugs: {
            restaurant: "biryani-day-thulsi-theater-road-marathahalli",
            city: "bangalore",
          },
          cityState: "1",
          address: "No 389/2, 7th Cross, Thulsi Theater Road, Marathalli",
          locality: "Thulsi Theater Road",
          parentId: 2635,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 8600,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 8600,
            message: "",
            title: "Delivery Charge",
            amount: "8600",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7.5 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "20% OFF",
            subHeader: "UPTO ₹50",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "1221",
            deliveryTime: 30,
            minDeliveryTime: 30,
            maxDeliveryTime: 30,
            lastMileTravel: 7.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.7",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "262167",
          name: "Hotel Empire",
          uuid: "c087d70f-5cff-49ec-8b8a-e8b1a07a1977",
          city: "1",
          area: "Brookefields",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "weuqdjwzk3azoijehnel",
          cuisines: ["North Indian", "Kebabs", "Biryani"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 35,
          minDeliveryTime: 35,
          maxDeliveryTime: 35,
          slaString: "35 MINS",
          lastMileTravel: 5.5,
          slugs: {
            restaurant: "hotel-empire-marathahalli-marathahalli",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "EMPIRE RESTAURANT ASK TOWERS,NO 7/3 OF THOOBARAHALLI VILLAGE,VARTHUR VILLAGE,VARTHOOR HOBLI 560037",
          locality: "",
          parentId: 475,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 6600,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 6600,
            message: "",
            title: "Delivery Charge",
            amount: "6600",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "5.5 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "10% OFF",
            subHeader: "UPTO ₹40",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "262167",
            deliveryTime: 35,
            minDeliveryTime: 35,
            maxDeliveryTime: 35,
            lastMileTravel: 5.5,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.9",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "422600",
          name: "Third Wave Coffee",
          uuid: "d3cb42c3-2c23-429f-abdb-c36847aed905",
          city: "1",
          area: "Mahadevpura",
          totalRatingsString: "100+ ratings",
          cloudinaryImageId: "0dca660dbdf2e04f9b861c4426ffd41e",
          cuisines: ["Beverages", "Bakery", "Continental"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          slaString: "36 MINS",
          lastMileTravel: 7.699999809265137,
          slugs: {
            restaurant: "third-wave-coffee-roasters-mahadevpura-mahadevpura",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "Phoenix Market City, First floor No 40 & 41, Whitefield Main Road, Mahadebapura, Dyavasandra Industrial Area, Krishnarajapuram Hubli, Bengaluru, K R Puram, B.B.M.P East, Karnataka-560048",
          locality: "Phoenix Market City",
          parentId: 274773,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 8600,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 8600,
            message: "",
            title: "Delivery Charge",
            amount: "8600",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=6948795~p=13~eid=00000188-96ed-70c5-0710-ca8c004c0d39",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7.6 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "30% OFF",
            subHeader: "UPTO ₹75",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "422600",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 7.699999809265137,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "4.1",
          totalRatings: 100,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "636313",
          name: "The Rameshwaram Cafe",
          uuid: "ee7e2a22-42c6-4f59-b0a1-d1df6faf403d",
          city: "1",
          area: "Brookefield",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "0adee855c65fa947a256764a87a55658",
          cuisines: ["South Indian"],
          tags: [],
          costForTwo: 25000,
          costForTwoString: "₹250 FOR TWO",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          slaString: "28 MINS",
          lastMileTravel: 6,
          slugs: {
            restaurant: "the-rameshwaram-café-whitefield-whitefield",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "AIKYAM - THE RAMESHWARAM CAFE PLOT NO. 01, ITPL MAIN ROAD, GREEN AVENUE - BENGALURU, INDIA, B.B.M.P East, Karnataka-560037",
          locality: "ITPL Main road",
          parentId: 384316,
          unserviceable: false,
          veg: true,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 7600,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 7600,
            message: "",
            title: "Delivery Charge",
            amount: "7600",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "6 kms",
          hasSurge: false,
          sla: {
            restaurantId: "636313",
            deliveryTime: 28,
            minDeliveryTime: 28,
            maxDeliveryTime: 28,
            lastMileTravel: 6,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.6",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "178387",
          name: "Hyderabadi Handi Biryani",
          uuid: "e6832cc6-4c6c-4976-a00b-f545b6de2fdf",
          city: "1",
          area: "Marathahalli",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "ewzw2m8whkincsto9kqm",
          cuisines: [
            "Biryani",
            "North Indian",
            "Desserts",
            "Tandoor",
            "Hyderabadi",
            "Andhra",
          ],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          slaString: "36 MINS",
          lastMileTravel: 7.300000190734863,
          slugs: {
            restaurant: "hyderabadi-handi-biryani-marathahalli-marathahalli",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "New Address No.32,ckb layout, munekolola, marthahali, Bangalore-37.",
          locality: "CKB Layout",
          parentId: 11087,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "distance",
                fee: 8600,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 8600,
            message: "",
            title: "Delivery Charge",
            amount: "8600",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 1,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7.3 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "40% OFF",
            subHeader: "UPTO ₹80",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "178387",
            deliveryTime: 36,
            minDeliveryTime: 36,
            maxDeliveryTime: 36,
            lastMileTravel: 7.300000190734863,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "IT_IS_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.5",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "14986",
          name: "Behrouz Biryani",
          uuid: "a3eb3cdc-61fc-47f7-8253-1c84717472fe",
          city: "1",
          area: "Whitefield",
          totalRatingsString: "5000+ ratings",
          cloudinaryImageId: "wi5nwv9nj1xrfikpyq7w",
          cuisines: [
            "Biryani",
            "Mughlai",
            "Lucknowi",
            "Hyderabadi",
            "Kebabs",
            "North Indian",
            "Desserts",
            "Beverages",
          ],
          tags: [],
          costForTwo: 50000,
          costForTwoString: "₹500 FOR TWO",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          slaString: "23 MINS",
          lastMileTravel: 1.2000000476837158,
          slugs: {
            restaurant: "behrouz-biryani-whitefield-main-road-whitefield",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "No 14/P1 1st Floor UMASHANKAR AVENUE, HAGDUR  ROAD WHITEFIELD  BANGALORE 560066",
          locality: "HAGDUR  ROAD",
          parentId: 1803,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          ribbon: [
            {
              type: "PROMOTED",
            },
          ],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3300,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3300,
            message: "",
            title: "Delivery Charge",
            amount: "3300",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID:
            "cid=7063084~p=16~eid=00000188-96ed-70c5-0710-ca8d004c106c",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.2 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "60% OFF",
            subHeader: "UPTO ₹120",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "14986",
            deliveryTime: 23,
            minDeliveryTime: 23,
            maxDeliveryTime: 23,
            lastMileTravel: 1.2000000476837158,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: true,
          avgRating: "3.9",
          totalRatings: 5000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "372897",
          name: "Pizza Hut",
          uuid: "3d837fdb-779a-4367-baf6-52fcf4d3e934",
          city: "1",
          area: "Whitefield",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
          cuisines: ["Pizzas"],
          tags: [],
          costForTwo: 30000,
          costForTwoString: "₹300 FOR TWO",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          slaString: "31 MINS",
          lastMileTravel: 2.0999999046325684,
          slugs: {
            restaurant: "pizza-hut-ramangondanhalli-whitefield",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "640/ 557, Ground Floor, Ramangondanhalli Village, Varthur Hobli, East taluk, Bangalore 560066",
          locality: "Whitefield",
          parentId: 721,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3300,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3300,
            message: "",
            title: "Delivery Charge",
            amount: "3300",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "2 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "₹125 OFF",
            subHeader: "ABOVE ₹399",
            discountTag: "FLAT DEAL",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "372897",
            deliveryTime: 31,
            minDeliveryTime: 31,
            maxDeliveryTime: 31,
            lastMileTravel: 2.0999999046325684,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.0",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "418",
          name: "Ande Ka Funda",
          uuid: "80f87c90-b6f4-48ef-b110-9bbfad549b39",
          city: "1",
          area: "Kadubeesanahalli",
          totalRatingsString: "10000+ ratings",
          cloudinaryImageId: "hwnvirxf8oxaubiflcag",
          cuisines: ["North Indian"],
          tags: [],
          costForTwo: 10000,
          costForTwoString: "₹100 FOR TWO",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          slaString: "33 MINS",
          lastMileTravel: 7,
          slugs: {
            restaurant:
              "ande-ka-funda-shymala-reddy-dental-college-road-marathahalli",
            city: "bangalore",
          },
          cityState: "1",
          address: "6, Shymala Reddy Dental College Road, Marathahalli",
          locality: "Munnekolala",
          parentId: 15677,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 8600,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 8600,
            message: "",
            title: "Delivery Charge",
            amount: "8600",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "7 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "20% OFF",
            subHeader: "UPTO ₹50",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "418",
            deliveryTime: 33,
            minDeliveryTime: 33,
            maxDeliveryTime: 33,
            lastMileTravel: 7,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.5",
          totalRatings: 10000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "634166",
          name: "Burger King",
          uuid: "f3834a94-916d-453c-ab25-f41e43886ad2",
          city: "1",
          area: "Whitefield",
          totalRatingsString: "1000+ ratings",
          cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
          cuisines: ["Burgers", "American"],
          tags: [],
          costForTwo: 35000,
          costForTwoString: "₹350 FOR TWO",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          slaString: "32 MINS",
          lastMileTravel: 1.2999999523162842,
          slugs: {
            restaurant: "burger-king-nexus-whitefield-mall-whitefield",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "FC-11 3rd floor,Nexus Whitefield Mal,  Whitefield, Bengaluru, Karnataka 560066",
          locality: "Nexus Whitefield Mall",
          parentId: 166,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3300,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3300,
            message: "",
            title: "Delivery Charge",
            amount: "3300",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "1.2 kms",
          hasSurge: false,
          aggregatedDiscountInfoV3: {
            header: "60% OFF",
            subHeader: "UPTO ₹120",
            discountTag: "",
            headerTypeV2: 0,
          },
          sla: {
            restaurantId: "634166",
            deliveryTime: 32,
            minDeliveryTime: 32,
            maxDeliveryTime: 32,
            lastMileTravel: 1.2999999523162842,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "3.9",
          totalRatings: 1000,
          new: false,
        },
        subtype: "basic",
      },
      {
        type: "restaurant",
        data: {
          type: "F",
          id: "707063",
          name: "KFC",
          uuid: "f2cc7ecf-a5e3-40f1-a396-c545ffb79f83",
          city: "1",
          area: "Varthur",
          totalRatingsString: "50+ ratings",
          cloudinaryImageId: "d1d49a5694149063c00d38f9b17c923c",
          cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
          tags: [],
          costForTwo: 40000,
          costForTwoString: "₹400 FOR TWO",
          deliveryTime: 17,
          minDeliveryTime: 17,
          maxDeliveryTime: 17,
          slaString: "17 MINS",
          lastMileTravel: 2.700000047683716,
          slugs: {
            restaurant: "kfc-ramagondanahalli-varthur-gunjur",
            city: "bangalore",
          },
          cityState: "1",
          address:
            "704, Patel Complex,Opp To Laughing Water, Ramagondanahalli, WhiteField Main Road , Bengaluru560066",
          locality: "Ramagondanahalli",
          parentId: 547,
          unserviceable: false,
          veg: false,
          select: false,
          favorite: false,
          tradeCampaignHeaders: [],
          chain: [],
          feeDetails: {
            fees: [
              {
                name: "distance",
                fee: 3300,
                message: "",
              },
              {
                name: "time",
                fee: 0,
                message: "",
              },
              {
                name: "special",
                fee: 0,
                message: "",
              },
            ],
            totalFees: 3300,
            message: "",
            title: "Delivery Charge",
            amount: "3300",
            icon: "",
          },
          availability: {
            opened: true,
            nextOpenMessage: "",
            nextCloseMessage: "",
          },
          longDistanceEnabled: 0,
          rainMode: "NONE",
          thirdPartyAddress: false,
          thirdPartyVendor: "",
          adTrackingID: "",
          badges: {
            imageBased: [],
            textBased: [],
            textExtendedBadges: [],
          },
          lastMileTravelString: "2.7 kms",
          hasSurge: false,
          sla: {
            restaurantId: "707063",
            deliveryTime: 17,
            minDeliveryTime: 17,
            maxDeliveryTime: 17,
            lastMileTravel: 2.700000047683716,
            lastMileDistance: 0,
            serviceability: "SERVICEABLE",
            rainMode: "NONE",
            longDistance: "NOT_LONG_DISTANCE",
            preferentialService: false,
            iconType: "EMPTY",
          },
          promoted: false,
          avgRating: "4.1",
          totalRatings: 50,
          new: true,
        },
        subtype: "basic",
      },
    ];
    data.forEach((rest) => {
      console.log(rest?.data?.name);
      console.log(rest?.data?.cloudinaryImageId),
        console.log(rest?.data?.cuisines);
      console.log(rest?.data?.lastMileTravelString);
      // repo.create({
      //   name: rest?.data?.name,
      //   url: rest?.data?.cloudinaryImageId,
      //   restaurantId: rest?.data?.id,
      //   ratings: i,
      // });
    });

    const DB_SYNC = false;
    if (DB_SYNC) {
      db.sequelize.sync({ alter: true });
    }
  });
};

setupAndStartServer();
